# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title: Jasmine Mangic
tagline: 'Administration & Business Support Professional'
description: 'Administration & Business Support professional with 9+ years experience supporting teams through coordination, compliance and operational support.'
url:              https://jasmine-mangic.github.io
baseurl:          ""

author:
  name:           'Jasmine Mangic'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: null
